name:                mtl-bench
version:             0.1.0.0
github:              "psibi/mtl-bench"
license:             BSD3
author:              "Sibi Prabakaran"
maintainer:          "sibi@psibi.in"
copyright:           "Sibi Prabakaran"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psibi/mtl-bench#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src

tests:
  mtl-bench-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtl-bench

benchmarks:
  mtlbench:
    main: main.hs
    source-dirs: bench
    dependencies:
    - gauge
    - deepseq
    - mtl-bench
    ghc-options:
    - -O2
